name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger only on version tags

permissions:
  contents: write # Needed for uploading release assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Match your Go version

      - name: Build amd64 binary
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/speculator-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
